version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tictactoe
    networks:
      - tictactoe_network

  backend:
    build: ./backend
    container_name: tic_tac_toe_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://admin:password@mongodb:27017/tictactoe?authSource=admin"
    networks:
      - tictactoe_network
    volumes:
      - ./backend:/app
    command: /app/wait-for-mongo.sh  # Custom script to wait for MongoDB readiness

volumes:
  mongo_data:

networks:
  tictactoe_network:
    driver: bridge
