services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restar: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    
    backend:
      build: ~